"""
Memory (RAG) Agent Node.
This is the SECOND node in the LangGraph Incident Resolution Pipeline.
Its job is to take the hypothesis generated by the CorrelationAgent,
embed it using our local sentence-transformers model, and query Pinecone
to fetch similar historical incidents to give the LLM context.
"""

from graph.workflow_state import IncidentState
from langchain_core.runnables import RunnableConfig
from database.pinecone import vector_store
from rag.embeddings import embeddings

class MemoryAgent:
    
    @staticmethod
    def run(state: IncidentState, config: RunnableConfig) -> IncidentState:
        """
        Executes Semantic Memory retrieval.
        It generates a dense vector representing the current failure and fetches
        similar vectors from Pinecone to retrieve historical resolutions.
        """
        hypothesis = state["initial_hypothesis"]
        historical_context = "No historical context found."
        
        if vector_store.index:
            try:
                # 1. Embed the hypothesis string into a dense vector
                query_vec = embeddings.encode(hypothesis)
                # 2. Query the Pinecone Index for the Top-2 closest historical incidents
                res = vector_store.index.query(vector=query_vec, top_k=2, include_metadata=True)
                
                # 3. Format the retrieved memories for the LLM prompt
                if res and "matches" in res and res["matches"]:
                    contexts = []
                    for match in res["matches"]:
                        meta = match.get("metadata", {})
                        contexts.append(f"Past RCA: {meta.get('root_cause')} -> Action Taken: {meta.get('action_taken')}")
                    historical_context = "\n".join(contexts)
            except Exception as e:
                print(f"⚠️ [MemoryAgent] RAG Query Failed: {e}")
                
        # Pass the newly acquired context to the ReasoningAgent
        return {"historical_context": historical_context}
